package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.Phong;
import service.PhongServce;
import service.impl.PhongServceImpl;
import viewmodel.DinhVuPhong;
import viewmodel.KhachThuePhong;
import viewmodel.PhongView;
import viewmodel.ThietBiPhong;

/**
 *
 * @author ASUS
 */
public class RoomCard extends javax.swing.JPanel {

    private PhongServce phongServce = new PhongServceImpl();
    PhongView view;
    CardLayout cardLayout = new CardLayout();
    private PhongJframe parent;

    public RoomCard(PhongView view) {
        initComponents();
        this.view = view;
        init();
        mauSacCard();
        loadSoNguoi(phongServce.getSoNguoi(txtTenPhong.getText()));
        isContractCreated();
    }

    private void isContractCreated() {
        int so = Integer.parseInt(lblSo.getText());
        if (so >= 1) {
            btnHopDong.setVisible(false);
            btnPhuThuoc.setVisible(true);
        } else {
            btnHopDong.setVisible(true);
            btnPhuThuoc.setVisible(false);
        }
    }

    public void mauSacCard() {

        if (txtTrangThai.getText().equals("Còn Trống")) {
            pnl.setBackground(new Color(215, 233, 186));
        } else {
            pnl.setBackground(new Color(248, 135, 127)); // thiết lập màu đỏ nếu phòng đã đầy
        }
    }

    private void loadSoNguoi(List<KhachThuePhong> list) {
        for (KhachThuePhong khachThuePhong : list) {
            lblSo.setText(String.valueOf(khachThuePhong.getId()));
        }
    }

    public void init() {
        txtTrangThai.setText(view.getTrangThai());
        txtGia.setText(String.valueOf(view.getGiaPhong()));
        txtTenPhong.setText(view.getMaPhong());
        txtSoLuong.setText(String.valueOf(view.getSoLuongNguoi()));
        txtTang.setText(view.getKhuVuc());
        txtDienTich.setText(String.valueOf(view.getDienTich()));
        txtLoaiPhong.setText(view.getLoaiPhong());
    }

    public void setParent(PhongJframe parent) {
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        btnChiTiet = new javax.swing.JMenuItem();
        btnTraPhong = new javax.swing.JMenuItem();
        btnHopDong = new javax.swing.JMenuItem();
        btnCapNhap = new javax.swing.JMenuItem();
        btnPhuThuoc = new javax.swing.JMenuItem();
        pnl = new javax.swing.JPanel();
        txtTang = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDienTich = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLoaiPhong = new javax.swing.JLabel();
        lblTienNha = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JLabel();
        txtGia = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        btnChiTiet.setText("Xem Phòng");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });
        jPopupMenu1.add(btnChiTiet);

        btnTraPhong.setText("Trả Phòng");
        jPopupMenu1.add(btnTraPhong);

        btnHopDong.setText("Tạo Hợp Đồng");
        btnHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHopDongActionPerformed(evt);
            }
        });
        jPopupMenu1.add(btnHopDong);

        btnCapNhap.setText("Cập Nhập");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });
        jPopupMenu1.add(btnCapNhap);

        btnPhuThuoc.setText("Thêm người phụ thuộc");
        btnPhuThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhuThuocActionPerformed(evt);
            }
        });
        jPopupMenu1.add(btnPhuThuoc);

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        txtTang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTang.setText("jLabel7");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Diện Tích");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tên Phòng: ");

        txtDienTich.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDienTich.setText("jLabel7");

        txtTenPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTenPhong.setText("jLabel2");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Loại Phòng");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Trạng Thái:");

        txtLoaiPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLoaiPhong.setText("jLabel7");

        txtTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTrangThai.setText("jLabel5");

        txtGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtGia.setText("jLabel6");

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSoLuong.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tầng");

        lblSo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSo.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("/");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Triệu");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Khách");

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(lblTienNha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtTang, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(45, 45, 45)
                        .addComponent(txtLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(54, 54, 54)
                        .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtTenPhong))
                .addGap(35, 35, 35)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTang))
                .addGap(33, 33, 33)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtLoaiPhong))
                .addGap(44, 44, 44)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtDienTich))
                .addGap(28, 28, 28)
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtTrangThai))
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblSo)
                                        .addComponent(jLabel4)
                                        .addComponent(txtSoLuong)
                                        .addComponent(jLabel9))))))
                    .addComponent(lblTienNha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 317, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (SwingUtilities.isRightMouseButton(evt)) {
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMousePressed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        ChiTietPhongTro ct = new ChiTietPhongTro();
        List<PhongView> list = phongServce.getALL();
        if (list.size() >= 0) {
            List<KhachThuePhong> listLoad = phongServce.getKhachThuePhong(txtTenPhong.getText());
            ct.loadTableKhachThuePhong(listLoad);
            List<DinhVuPhong> dinhVuPhong = phongServce.getDinhVuPhong(txtTenPhong.getText());
            ct.loadTableDinhVu(dinhVuPhong);
            List<ThietBiPhong> thietBiPhong = phongServce.getThietBiPhong(txtTenPhong.getText());
            ct.loadTableThietBi(thietBiPhong);
            for (int i = 0; i < list.size(); i++) {
                ct.getMaPhong().setText(list.get(i).getMaPhong());
                ct.getKhuVuc().setText(list.get(i).getKhuVuc());
                ct.getLoaiPhong().setText(list.get(i).getLoaiPhong());
                ct.getSoNguoiToiDa().setText(String.valueOf(list.get(i).getSoLuongNguoi()));
                ct.getDienTich().setText(String.valueOf(list.get(i).getDienTich()));
                ct.getGiaPhong().setText(String.valueOf(list.get(i).getGiaPhong()));
                ct.getTrangThai().setSelectedItem(txtTrangThai.getText());
            }
        }
        ct.setDefaultCloseOperation(FromHopDong.DO_NOTHING_ON_CLOSE);
        ct.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Xử lý sự kiện đóng cửa sổ form b mà không tắt form a
                ct.setVisible(false);
            }
        });
        ct.setVisible(true);
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void btnHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHopDongActionPerformed
        if (txtTrangThai.getText().equals("Đã Đủ")) {
            JOptionPane.showMessageDialog(this, "Phòng đã đủ");
        } else if (Integer.parseInt(lblSo.getText()) == Integer.parseInt(txtSoLuong.getText())) {
            JOptionPane.showMessageDialog(this, "Phòng Đã Full Người Không Thể Thêm Người Vào Phòng");
        } else {
            FromHopDong fromHopDong = new FromHopDong();
            fromHopDong.getMaPhong().setText(txtTenPhong.getText());
            fromHopDong.getKhuVuc().setText(txtTang.getText());
            fromHopDong.getLoaiPhong().setText(txtLoaiPhong.getText());
            fromHopDong.getSoNguoiToiDa().setText(txtSoLuong.getText());
            fromHopDong.getDienTich().setText(txtDienTich.getText());
            fromHopDong.getGiaPhong().setText(txtGia.getText());
            fromHopDong.setDefaultCloseOperation(FromHopDong.DO_NOTHING_ON_CLOSE);
            fromHopDong.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    // Xử lý sự kiện đóng cửa sổ form b mà không tắt form a
                    fromHopDong.setVisible(false);
                }
            });
            fromHopDong.setVisible(true);
        }
    }//GEN-LAST:event_btnHopDongActionPerformed

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        ChinhSuaPhong csp = new ChinhSuaPhong();

        Phong phong = phongServce.getOneMoTa(txtTenPhong.getText());
        csp.getMaPhong().setText(txtTenPhong.getText());
        csp.getKhuVuc().setSelectedItem(txtTang.getText());
        csp.getLoaiPhong().setSelectedItem(txtLoaiPhong.getText());
        csp.getSoNguoiToiDa().setText(txtSoLuong.getText());
        csp.getDienTich().setText(txtDienTich.getText());
        csp.getGiaPhong().setText(txtGia.getText());
        csp.getTrangThai().setSelectedItem(txtTrangThai.getText());
        csp.getMoTa().setText(phong.getMoTa());
        csp.setDefaultCloseOperation(FromHopDong.DO_NOTHING_ON_CLOSE);
        csp.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Xử lý sự kiện đóng cửa sổ form b mà không tắt form a
                csp.setVisible(false);
            }
        });
        csp.setVisible(true);
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void btnPhuThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhuThuocActionPerformed
        ThemNguoiPhuThuoc nguoiPhuThuoc = new ThemNguoiPhuThuoc();
        nguoiPhuThuoc.getTen().setText(txtTenPhong.getText());
        nguoiPhuThuoc.getGia().setText(txtGia.getText());
        nguoiPhuThuoc.setDefaultCloseOperation(nguoiPhuThuoc.DO_NOTHING_ON_CLOSE);
        nguoiPhuThuoc.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Xử lý sự kiện đóng cửa sổ form b mà không tắt form a
                nguoiPhuThuoc.setVisible(false);
            }
        });
        nguoiPhuThuoc.setVisible(true);
    }//GEN-LAST:event_btnPhuThuocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCapNhap;
    private javax.swing.JMenuItem btnChiTiet;
    private javax.swing.JMenuItem btnHopDong;
    private javax.swing.JMenuItem btnPhuThuoc;
    private javax.swing.JMenuItem btnTraPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblSo;
    private javax.swing.JLabel lblTienNha;
    private javax.swing.JPanel pnl;
    private javax.swing.JLabel txtDienTich;
    private javax.swing.JLabel txtGia;
    private javax.swing.JLabel txtLoaiPhong;
    private javax.swing.JLabel txtSoLuong;
    private javax.swing.JLabel txtTang;
    private javax.swing.JLabel txtTenPhong;
    private javax.swing.JLabel txtTrangThai;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getTenPhong() {

        return txtTenPhong;
    }

    public javax.swing.JLabel getTienNha() {

        return txtGia;
    }
}
